container: jenkins-ci-php
install:
	- source /etc/profile.d/phpbrew
	- phpbrew switch 5.6.3
	- phpbrew install-composer
	- phpbrew install-phpunit
	- phpbrew ext install xdebug
	- composer install
script:
	- phpunit