container: jenkins-ci-base
env:
    - NAME: Jenkins
install:
    - yum install http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
    - yum install -y nginx
    - service nginx start
script:
    - echo "Hello ${NAME}"

after_script:
    - curl http://localhost:80
