container: aozora0000/jenkins-ci-php
steps:
    - name: composerインストール
      code: composer update
    - name: PHPUNIT起動
      code: phpunit
notify:
    - service: idobata
      token: $IDOBATA_TOKEN
    - service: irc
      room_id: test
      ikachan: http://localhost:4649
