container: aozora0000/jenkins-ci-php
links:
    - name: redis
      container: redis
steps:
    - name: env表示
      code: env
    - name: php-redisインストール
      code: phpbrew -q ext install redis
    - name: composerインストール
      code: composer update
    - name: PHPUNIT起動
      code: phpunit
notify:
    - service: idobata
      token: $IDOBATA_TOKEN
    - service: chatwork
      token: $CHATWORK_TOKEN
      room_id: $CHATWORK_ROOM_ID
