container: aozora0000/jenkins-ci-php
steps:
    - name: composerインストール
      code: composer update
    - name: PHPUNIT起動
      code: phpunit
notify:
    - service: idobata
      token: $IDOBATA_TOKEN
    - service: hipchat
      token: $HIPCHAT_TOKEN
      room_id: $HIPCHAT_ROOM_ID
      from: Jenkins
