container: jenkins-ci-php
install:
	- source /etc/profile.d/phpbrew
	- phpbrew switch 5.6.3
	- phpbrew composer-install
	- phpbrew phpunit-install
	- phpbrew ext install xdebug
	- composer install
script:
	- phpunit