container: aozora0000/jenkins-ci-php
steps:
    - name: composerインストール
      code: composer update
    - name: PHPUNIT起動
      code: phpunit
notify:
    - service: idobata
      token: 4f18052e-28cb-447a-9704-c12cff0575d4